USE [WorkBuddies]
GO

insert into Buddy (Id, FirstName, LastName, Email, City, [State], [Image], About, Gender, Age, CompanyName, CompanyIndustry, CompanyRole, FirebaseUserId) values (1, 'Benny', 'Profane', 'bennyprofane@workbuddies.com', 'Nashville', 'TN', 'https://preview.redd.it/askikll0e0h31.jpg?width=640&crop=smart&auto=webp&v=enabled&s=ea9f13bf7a8873c3ef01cb00c8de523530f86593', 'Wearing black Levis, suede jacket, sneakers and big cowboy hat, passing through Norfolk, Virginia.', 'Male', 24, 'Ubuloo', 'Pataphysics', 'Testing', 'rUIBiJA7L5PnZMYFSD6e2oTQ3aP2');
insert into Buddy (Id, FirstName, LastName, Email, City, [State], [Image], About, Gender, Age, CompanyName, CompanyIndustry, CompanyRole, FirebaseUserId) values (2, 'Rachel', 'Owlglass', 'rachelowlglass@workbuddies.com', 'Nashville', 'TN', 'https://thumbnailer.mixcloud.com/unsafe/300x300/extaudio/3/1/0/f/a515-10b2-41f6-9698-959b8e60faa9', 'The true king only dies a mock death. Any number of young men may be selected to die in his place while the real king, foxy old b&st*rd, goes on.', 'Female', 22, 'Ubuloo', 'Pataphysics', 'Lead Developer', 'E4zDXozWeGYeloZRYsGmRazR3H63');
insert into Buddy (Id, FirstName, LastName, Email, City, [State], [Image], About, Gender, Age, CompanyName, CompanyIndustry, CompanyRole, FirebaseUserId) values (3, 'Chevrolette', 'McAdoo', 'chevrolettemcadoo@workbuddies.com', 'Nashville', 'TN', 'https://i0.wp.com/bamfstyle.com/wp-content/uploads/2021/12/MoroccoMD-MAIN1.jpg?resize=768%2C1182&ssl=1', 'A walk-on part in a leagues-distant land.',  'Female', 34, 'Jinx', 'Renewables', 'Surveyor', '6BxCuyFVYNRAIIg7pnWgDFgSjp23');
insert into Buddy (Id, FirstName, LastName, Email, City, [State], [Image], About, Gender, Age, CompanyName, CompanyIndustry, CompanyRole, FirebaseUserId) values (4, 'Roger', 'Mexico', 'rogermexico@workbuddies.com', 'Knoxville', 'TN', 'https://pbs.twimg.com/profile_images/1483893107003428868/o4cwSUzh_400x400.jpg', 'Everyone is equal. Same chances of getting hit. Equal in the eyes of the rocket.', 'Male', 28, 'Latterday', 'Transport', 'Logistical Officer', 'Wz8LRE8e7GWBoI2JQ3PJZaM4i0R2');
insert into Buddy (Id, FirstName, LastName, Email, City, [State], [Image], About, Gender, Age, CompanyName, CompanyIndustry, CompanyRole, FirebaseUserId) values (5, 'Tyrone', 'Slothrop', 'tyroneslothrop@workbuddies.com', 'Knoxville', 'TN', 'http://4.bp.blogspot.com/-mTcLAdySZOY/TWZuJqmRykI/AAAAAAAAEmg/4qIm-eL3YEo/s400/death.jpg', 'But out here, down here among the people, the truer currencies come into being.', 'Male', 40, 'Eurowan', 'Online Dating', 'Compatibility Specialist', 'EOImlg7BNkZxIf01WF5m6FWvZRI3');

insert into Vibe (Id, [Name]) values (1, 'Relaxing');
insert into Vibe (Id, [Name]) values (2, 'Frantic');
insert into Vibe (Id, [Name]) values (3, 'Popping');